project:
  type: website

website:
  title: "99 Euler Problems"
  sidebar:
    style: docked
    search: true
    contents: auto

format:
  html:
    theme: cosmo
    css: styles.css
    toc: true
    code-tools: true
    code-annotations: below

execute:
  cache: true
  freeze: auto
